version: '3'

services:
  openmrs-mysql-facilityName-fosaCode:
      container_name: openmrs-mysql-facilityName-fosaCode
      image: savicsorg/openmrs-mysql1911:v1.1
      volumes:
        - ./disc/mysql/facilityName-fosaCode-data:/var/lib/mysql
      ports:
        - "3333:3306"
      restart: always
      logging:
        options:
          max-size: 5m
      deploy:
        resources:
          limits:
            memory: 2048M
          reservations:
            memory: 1024M
    

  openmrs-tomcat-facilityName-fosaCode:
    container_name: openmrs-tomcat-facilityName-fosaCode
    image: savicsorg/openmrs-tomcat1911:v1.2
    volumes:
      - ./disc/openmrs/facilityName-fosaCode-data:/root/.OpenMRS/
    ports:
      - "8888:8080"
    depends_on:
      - openmrs-mysql-facilityName-fosaCode
    restart: always
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
