openmrs-tomcat:
  image: savicsorg/openmrs-tomcat1911:v1.1
  ports:
    - "8081:8080"
  container_name: openmrs-tomcat
  links:
    - openmrs-mysql
openmrs-mysql:
  image: savicsorg/openmrs-mysql1911:v1.1
  ports:
    - "3307:3306"
  container_name: openmrs-mysql
